### ISSUE TITLE
Problems in executing "predict_probe_offtarget"

### ISSUE THREAD

**Issue by sammywinchester19** [hym0405/RNaseH_depletion#3]
Hi,

I am trying a test run with the data already available in the RNaseH_rRNA depletion tool but its seems that there is some problem I am encountering. Can you please let me know what mistake I am making here ?

Suleman 
PhD student.

**Script**
./2.predict_probe_offtarget.py -t ./data/transcriptome_annotation/dorei.ffn -r ./data/transcriptome_annotation/dorei.rRNA.list -p ./output/Mock/rRNA_probe.dorei.fa -pf FASTA -o ./output/test_probes -mb ./bin/makeblastdb -bn ./bin/blastn -br ./bin/burst

**Error**
Building a new DB, current time: 09/29/2020 19:28:21
New DB name:   /home/suleman/Desktop/My_desktop/Programs/RNaseH_depletion-master/.tmp_offtarget_predict_RNaseH/target
New DB title:  ./.tmp_offtarget_predict_RNaseH/target.ffn
Sequence type: Nucleotide
Deleted existing Nucleotide BLAST database named /home/suleman/Desktop/My_desktop/Programs/RNaseH_depletion-master/.tmp_offtarget_predict_RNaseH/target
Keep MBits: T
Maximum file size: 1000000000B
Adding sequences from FASTA; added 4887 sequences in 0.295118 seconds.
Traceback (most recent call last):
  File "./2.predict_probe_offtarget.py", line 114, in <module>
    path_rRNAref, path_outputP + ".BLAST.tsv")
  File "./2.predict_probe_offtarget.py", line 38, in processBLASToutput
    tmp = each.split("\t")
TypeError: a bytes-like object is required, not 'str'

**Comment by hym0405** [comment]
Hi Suleman,

It could be the problem caused by version of python. The script was tested using Python2.7 and "2.predict_probe_offtarget.py" may not work using Python3. We plan to update our version in following months. Thank you very much!

Best,
Yiming

**Comment by sammywinchester19** [comment]
Hi,

Thanks the above test script worked fine with your data but when I attempt to load my own data it does not seem to go through.

**Scirpt**
./2.predict_probe_offtarget.py -t ./data/MY_DATA/Shewanella.ffn -r ./data/MY_DATA/Shewanella.rRNA.list -p ./data/MY_DATA/rRNA_probe.Shewanella.fa -pf FASTA -o ./output/S1_probes -mb ./bin/makeblastdb -bn ./bin/blastn -br ./bin/burst

**Error**


Building a new DB, current time: 09/30/2020 10:43:08
New DB name:   /home/suleman/Desktop/My_desktop/Programs/RNaseH_depletion-master/.tmp_offtarget_predict_RNaseH/target
New DB title:  ./.tmp_offtarget_predict_RNaseH/target.ffn
Sequence type: Nucleotide
Keep MBits: T
Maximum file size: 1000000000B
Adding sequences from FASTA; added 3937 sequences in 0.207763 seconds.
This is BURST [v0.99.8 special edition [PT2.5]]
Hotloading is disabled
 --> Also considering the reverse complement of reads
 --> Setting identity threshold to 0.800000
 --> Setting run mode to FORAGE
 --> Setting threads to 4
Using up to AVX-128 with 4 threads.
ERROR: line count != '>' * 2

Thank you for helping :). 

Suleman.

**Comment by sammywinchester19** [comment]
Thanks I fixed the issue :)
